# Generated by Django 5.2.5 on 2025-10-02 15:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.png', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
